apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configmap-filebeat
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configmap-properties-filebeat
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: filebeat-config
                  namespace: kube-system
                  labels:
                    k8s-app: filebeat
                data:
                  filebeat.yml: |-
                    filebeat.inputs:
                    - type: container
                      paths:
                        - /var/log/containers/*.log
                    processors:
                      - add_kubernetes_metadata:
                          host: ${NODE_NAME}
                          matchers:
                          - logs_path:
                              logs_path: "/var/log/containers/"
                    processors:
                      - add_cloud_metadata:
                      - add_host_metadata:
                    cloud.id: ${ELASTIC_CLOUD_ID}
                    cloud.auth: ${ELASTIC_CLOUD_AUTH}
                    output.elasticsearch:
                      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
                      username: ${ELASTICSEARCH_USERNAME}
                      password: ${ELASTICSEARCH_PASSWORD}
                      ssl.certificate_authorities:
                        - /etc/certificate/ca.crt
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-configmap-filebeat
placementRef:
  name: placement-configmap-filebeat
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-configmap-filebeat
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-configmap-filebeat
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
