apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configure-filebeat-rbac
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configure-filebeat-rbac-app
        spec:
          remediationAction: inform # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: filebeat
                subjects:
                  - kind: ServiceAccount
                    name: elastic-operators
                    namespace: kube-system
                roleRef:
                  kind: ClusterRole
                  name: filebeat
                  apiGroup: rbac.authorization.k8s.io
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: filebeat
                  namespace: kube-system
                subjects:
                  - kind: ServiceAccount
                    name: elastic-operators
                    namespace: kube-system
                roleRef:
                  kind: Role
                  name: filebeat
                  apiGroup: rbac.authorization.k8s.io
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: filebeat-kubeadm-config
                  namespace: kube-system
                subjects:
                  - kind: ServiceAccount
                    name: filebeat
                    namespace: kube-system
                roleRef:
                  kind: Role
                  name: filebeat-kubeadm-config
                  apiGroup: rbac.authorization.k8s.io
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: filebeat
                  labels:
                    k8s-app: filebeat
                  rules:
                  - apiGroups: [""] # "" indicates the core API group
                    resources:
                    - namespaces
                    - pods
                    - nodes
                    verbs:
                    - get
                    - watch
                    - list
                  - apiGroups: ["apps"]
                    resources:
                      - replicasets
                    verbs: ["get", "list", "watch"]
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: filebeat
                    
                  namespace: kube-system
                  labels:
                    k8s-app: filebeat
                rules:
                - apiGroups:
                    - coordination.k8s.io
                  resources:
                    - leases
                  verbs: ["get", "create", "update"]
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: filebeat-kubeadm-config
                  namespace: kube-system
                  labels:
                    k8s-app: filebeat
                rules:
                - apiGroups: [""]
                  resources:
                    - configmaps
                  resourceNames:
                    - kubeadm-config
                  verbs: ["get"]
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ServiceAccount
                metadata:
                  name: elastic-operators
                  namespace: kube-system
                labels:
                  k8s-app: filebeat
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-configure-filebeat-rbac
placementRef:
  name: placement-policy-configure-filebeat-rbac
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-configure-filebeat-rbac
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-configure-filebeat-rbac
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
